---
# This playbook restarts the metaloggers one by one and waits for each to come up before moving to the next
# It checks health and allows you to take different actions based on that.
# By default it only upgrades metaloggers that are healthy and out of date.
# Currently it does not handle package upgrades as we are not using packages yet
# TODO - https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#comparing-versions should improve logic and code
- name: Rolling restart and upgrade of metaloggers
  hosts: moosefs_metalogger
  serial: 1
  become: true

  vars:
    moosefs_restart_metaloggers: true
    moosefs_restart_metaloggers_force: false
    moosefs_version: '3.0.115'

  pre_tasks:
    - name: Check the list of connected metalogger servers using mfscli
      command: mfscli -SMB -H {{ moosefs_master_host }} -p -s ' '
      register: moosefs_metalogger_status_list
      check_mode: false
      changed_when: false

    - name: Determine the current state of the metalogger
      set_fact:
        moosefs_metalogger_connected: "{{ moosefs_metalogger_status_list.stdout_lines | select('search', inventory_hostname) | length != 0 }}"
        moosefs_metalogger_version_match: "{{ moosefs_metalogger_status_list.stdout_lines | select('search', inventory_hostname) | select('search', moosefs_version) | length != 0 }}"
        moosefs_metalogger_upgrade_needed: "{{ moosefs_metalogger_status_list.stdout_lines | select('search', inventory_hostname) | select('search', moosefs_version) | length == 0 }}"

    - name: Print the current state of the metalogger
      debug:
        msg:
          - "Connected? {{ moosefs_metalogger_connected }}"
          - "Version matches target? {{ moosefs_metalogger_version_match }}"
          - "Upgrade needed? {{ moosefs_metalogger_upgrade_needed }}"

  tasks:
    - name: Restart metalogger service
      service:
        name: moosefs-metalogger
        state: restarted
      when:
        - moosefs_restart_metaloggers
        - moosefs_metalogger_upgrade_needed or moosefs_restart_metaloggers_force

  post_tasks:
    - name: Check the list of connected metalogger servers using mfscli
      command: mfscli -SMB -H {{ moosefs_master_host }} -p -s ' '
      register: moosefs_metalogger_status_list
      check_mode: false
      changed_when: false

    - name: Determine the current state of the metalogger
      set_fact:
        moosefs_metalogger_connected: "{{ moosefs_metalogger_status_list.stdout_lines | select('search', inventory_hostname) | length != 0 }}"
        moosefs_metalogger_version_match: "{{ moosefs_metalogger_status_list.stdout_lines | select('search', inventory_hostname) | select('search', moosefs_version) | length != 0 }}"
        moosefs_metalogger_upgrade_needed: "{{ moosefs_metalogger_status_list.stdout_lines | select('search', inventory_hostname) | select('search', moosefs_version) | length == 0 }}"

    - name: Print the current state of the metalogger
      debug:
        msg:
          - "Connected? {{ moosefs_metalogger_connected }}"
          - "Version matches target? {{ moosefs_metalogger_version_match }}"
          - "Upgrade needed? {{ moosefs_metalogger_upgrade_needed }}"

    - name: Prevent moving on if there was an issue
      assert:
        that:
          - moosefs_metalogger_connected
          - moosefs_metalogger_version_match
          - not moosefs_metalogger_upgrade_needed
