---
# This playbook restarts the chunkservers one by one and waits for each to come up before moving to the next
# It checks health and allows you to take different actions based on that.
# By default it only upgrades chunkservers that are healthy and out of date.
# Early version but nearly ready for primetime and has been tested on small systems
- name: Restart chunkservers
  hosts: moosefs_chunkserver
  serial: 1
  become: true

  vars_files:
    vars/upgrade-settings.yml

  pre_tasks:
    - name: Check the state of the chunk matrix before any changes
      command: mfscli -SIC -H {{ moosefs_master_host }} -p -s ' '
      register: moosefs_chunks_status
      check_mode: false
      changed_when: false

    - name: Check the list of all connected chunkservers using mfscli
      command: mfscli -SCS -H {{ moosefs_master_host }} -p -s ' '
      register: moosefs_chunkserver_status
      check_mode: false
      changed_when: false

    - name: Determine the current state of the chunk matrix
      set_fact:
        moosefs_chunks_missing: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass missing:') | select('search', ': 0') | length == 0 }}"
        moosefs_chunks_endangered: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass endangered:') | select('search', ': 0') | length == 0 }}"
        moosefs_chunks_undergoal: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass undergoal:') | select('search', ': 0') | length == 0 }}"

    - name: Determine the current state of the chunkserver
      set_fact:
        moosefs_chunkserver_connected: "{{ moosefs_chunkserver_status.stdout_lines | select('search', inventory_hostname) | length != 0 }}"
        moosefs_chunkserver_version_match: "{{ moosefs_chunkserver_status.stdout_lines | select('search', inventory_hostname) | select('search', moosefs_version) | length != 0 }}"
        moosefs_chunkserver_upgrade_needed: "{{ moosefs_chunkserver_status.stdout_lines | select('search', inventory_hostname) | select('search', moosefs_version) | length == 0 }}"

    - name: Print the current state of the chunk matrix
      debug:
        msg:
          - "Chunks missing? {{ moosefs_chunks_missing }}"
          - "Chunks endangered? {{ moosefs_chunks_endangered }}"
          - "Chunks undergoal? {{ moosefs_chunks_undergoal }}"

    - name: Print the current state of the chunkserver
      debug:
        msg:
          - "Connected? {{ moosefs_chunkserver_connected }}"
          - "Version matches target? {{ moosefs_chunkserver_version_match }}"
          - "Upgrade needed? {{ moosefs_chunkserver_upgrade_needed }}"

    - name: Give some feedback as to what will happen next
      debug:
        msg:
          - "Abort due to missing chunks: {{ moosefs_chunks_missing and moosefs_abort_on_missing_chunks }}"
          - "Abort due to endangered chunks: {{ moosefs_chunks_endangered and moosefs_abort_on_endangered_chunks }}"
          - "Abort due to undergoal chunks: {{ moosefs_chunks_undergoal and moosefs_abort_on_undergoal_chunks }}"

  tasks:
    - name: Restart chunkserver service
      service:
        name: moosefs-chunkserver
        state: restarted
      when:
        - moosefs_restart_chunkservers
        - moosefs_chunkserver_upgrade_needed or moosefs_restart_chunkservers_force
        - not (moosefs_chunks_missing and moosefs_abort_on_missing_chunks)
        - not (moosefs_chunks_endangered and moosefs_abort_on_endangered_chunks)
        - not (moosefs_chunks_undergoal and moosefs_abort_on_undergoal_chunks)

  post_tasks:
    - name: Check the state of the chunk matrix after our run
      command: mfscli -SIC -H {{ moosefs_master_host }} -p -s ' '
      register: moosefs_chunks_status
      check_mode: false
      changed_when: false

    - name: Determine the current state of the chunk matrix
      set_fact:
        moosefs_chunks_missing: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass missing:') | select('search', ': 0') | length == 0 }}"
        moosefs_chunks_endangered: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass endangered:') | select('search', ': 0') | length == 0 }}"
        moosefs_chunks_undergoal: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass undergoal:') | select('search', ': 0') | length == 0 }}"

    - name: Print the current state of the chunk matrix
      debug:
        msg:
          - "Chunks missing? {{ moosefs_chunks_missing }}"
          - "Chunks endangered? {{ moosefs_chunks_endangered }}"
          - "Chunks undergoal? {{ moosefs_chunks_undergoal }}"
