---
# This playbook restarts the metaloggers one by one and waits for each to come up before moving to the next
# Currently it does not handle package upgrades as we are not using packages yet
- name: Restart metaloggers for updates
  hosts: moosefs_metalogger
  serial: 1
  become: true

  vars:
    moosefs_restart_metaloggers: false

  pre_tasks:
    - name: Print the metalogger we are working with
      debug:
        msg:
          - "The metalogger we are working with is {{ inventory_hostname }} with IP {{ ansible_default_ipv4.address }}"

    - name: Check the list of connected metalogger servers using mfscli
      command: mfscli -SMB -H {{ moosefs_master_host }} -p -s ' '
      register: moosefs_metalogger_status_list
      check_mode: false
      changed_when: false

    - name: Print the list we just grabbed
      debug:
        msg:
          - "Connected metaloggers: {{ moosefs_metalogger_status_list.stdout_lines }}"

    - name: DEBUG - Check if the currently targeted metalogger is connected to the cluster
      debug:
        msg:
          - "inv hostname {{ inventory_hostname }}"
          - "{{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') }}"
          - "Connected? {{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') | length != 0 }}"
          - "Version? {{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') }}"
          - "Version match? {{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') | select('search', '3.0.115') | length != 0 }}"
          - "Upgrade needed? {{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') | select('search', '3.0.115') | length == 0 }}"

  tasks:
    - name: Restart metalogger service
      service:
        name: moosefs-metalogger
        state: restarted
      when: moosefs_restart_metaloggers

  post_tasks:
