---
# This playbook restarts the metaloggers one by one and waits for each to come up before moving to the next
# Currently it does not handle package upgrades as we are not using packages yet
- name: Restart metaloggers for updates
  hosts: moosefs_metalogger
  serial: 1
  become: true

  vars:
    moosefs_restart_metaloggers: false

  pre_tasks:
    - name: Print the metalogger we are working with
      debug:
        msg:
          - "The metalogger we are working with is {{ inventory_hostname }} with IP {{ ansible_default_ipv4.address }}"

    - name: Check the list of connected metalogger servers using mfscli
      command: mfscli -SMB -H {{ moosefs_master_host }} -p -s ' '
      register: moosefs_metalogger_status_list
      check_mode: false
      changed_when: false

    - name: Print the list we just grabbed
      debug:
        msg:
          - "Connected metaloggers: {{ moosefs_metalogger_status_list.stdout_lines }}"

    - name: DEBUG - Check if the currently targeted metalogger is connected to the cluster and other stuff
      debug:
        msg:
          - "inv hostname {{ inventory_hostname }}"
          - "{{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') }}"
          - "Connected? {{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') | length != 0 }}"
          - "Version? {{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') }}"
          - "Version match? {{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') | select('search', '3.0.115') | length != 0 }}"
          - "Upgrade needed? {{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') | select('search', '3.0.115') | length == 0 }}"

    # - name: Parse the list of connected metalogger servers and find relevant information about this metalogger
    #   set_fact:
    #     moosefs_metalogger

    - name: Determine the current state of the metalogger
      set_fact:
        moosefs_metalogger_connected: "{{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') | length != 0 }}"
        moosefs_metalogger_version_match: "{{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') | select('search', '3.0.115') | length != 0 }}"
        moosefs_metalogger_upgrade_needed: "{{ moosefs_metalogger_status_list.stdout_lines | select('search', 'blinky') | select('search', '3.0.115') | length == 0 }}"

    - name: Print the current state of the metalogger
      debug:
        msg:
          - "Connected? {{ moosefs_metalogger_connected }}"
          - "Version matches target? {{ moosefs_metalogger_version_match }}"
          - "Upgrade needed? {{ moosefs_metalogger_upgrade_needed }}"

  tasks:
    - name: Restart metalogger service
      service:
        name: moosefs-metalogger
        state: restarted
      when:
        - moosefs_restart_metaloggers
        - moosefs_metalogger_upgrade_needed or moosefs_restart_metaloggers_force

  post_tasks:
