---
# This playbook restarts the chunkservers one by one and waits for each to come up before moving to the next
# It checks health and allows you to take different actions based on that.
# By default it only upgrades metaloggers that are healthy and out of date.
# Currently it does not handle package upgrades as we are not using packages yet
# DO NOT USE YET JUST COPIED AND PASTED FROM METALOGGERS WITH A COUPLE TWEAKS
# todo - check chunk state before and after each chunkserver restart
# chunkclass endangered: 1300 (not do stuff if some chunks are endangered)
# chunkclass undergoal:	163472 (not do stuff if some chunks are undergoal)
# chunkclass missing: 0 (not do stuff if there are missing chunks unaccounted for)
# etc...

- name: Restart chunkservers
  hosts: moosefs_chunkserver
  serial: 1
  become: true

  vars:
    moosefs_restart_chunkservers: true
    moosefs_restart_chunkservers_force: true
    moosefs_chunkserver_upgrade_needed: false
    moosefs_abort_on_missing_chunks: true
    moosefs_abort_on_endangered_chunks: true
    moosefs_abort_on_undergoal_chunks: false
    moosefs_version: '3.0.115'

  pre_tasks:
    - name: Print the chunkserver we are working with
      debug:
        msg:
          - "The chunkserver we are working with is {{ inventory_hostname }} with IP {{ ansible_default_ipv4.address }}"

    - name: Check the state of the chunk matrix before any changes
      command: mfscli -SIC -H {{ moosefs_master_host }} -p -s ' '
      register: moosefs_chunks_status
      check_mode: false
      changed_when: false

    - name: Check the list of all connected chunkservers using mfscli
      command: mfscli -SCS -H {{ moosefs_master_host }} -p -s ' '
      register: moosefs_chunkserver_status_list
      check_mode: false
      changed_when: false

    - name: Determine the current state of the chunk matrix
      set_fact:
        moosefs_chunks_missing: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass missing:') | select('search', ': 0') | length == 0 }}"
        moosefs_chunks_endangered: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass endangered:') | select('search', ': 0') | length == 0 }}"
        moosefs_chunks_undergoal: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass undergoal:') | select('search', ': 0') | length == 0 }}"

    - name: Print the current state of the chunk matrix
      debug:
        msg:
          - "Chunks missing? {{ moosefs_chunks_missing }}"
          - "Chunks endangered? {{ moosefs_chunks_endangered }}"
          - "Chunks undergoal? {{ moosefs_chunks_undergoal }}"

    - name: Give some feedback as to what will happen next
      debug:
        msg:
          - "Abort due to missing chunks: {{ moosefs_chunks_missing and moosefs_abort_on_missing_chunks }}"
          - "Abort due to endangered chunks: {{ moosefs_chunks_endangered and moosefs_abort_on_endangered_chunks }}"
          - "Abort due to undergoal chunks: {{ moosefs_chunks_undergoal and moosefs_abort_on_undergoal_chunks }}"

  tasks:
    - name: Restart chunkserver service
      service:
        name: moosefs-chunkserver
        state: restarted
      when:
        - moosefs_restart_chunkservers
        - moosefs_chunkserver_upgrade_needed or moosefs_restart_chunkservers_force
        - not (moosefs_chunks_missing and moosefs_abort_on_missing_chunks)
        - not (moosefs_chunks_endangered and moosefs_abort_on_endangered_chunks)
        - not (moosefs_chunks_undergoal and moosefs_abort_on_undergoal_chunks)

  post_tasks:
    - name: Check the state of the chunk matrix after our run
      command: mfscli -SIC -H {{ moosefs_master_host }} -p -s ' '
      register: moosefs_chunks_status
      check_mode: false
      changed_when: false

    - name: Determine the current state of the chunk matrix
      set_fact:
        moosefs_chunks_missing: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass missing:') | select('search', ': 0') | length == 0 }}"
        moosefs_chunks_endangered: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass endangered:') | select('search', ': 0') | length == 0 }}"
        moosefs_chunks_undergoal: "{{ moosefs_chunks_status.stdout_lines | select('search', 'chunkclass undergoal:') | select('search', ': 0') | length == 0 }}"

    - name: Print the current state of the chunk matrix
      debug:
        msg:
          - "Chunks missing? {{ moosefs_chunks_missing }}"
          - "Chunks endangered? {{ moosefs_chunks_endangered }}"
          - "Chunks undergoal? {{ moosefs_chunks_undergoal }}"
