---
- name: Install MooseFS
  hosts: moosefs
  become: true

  vars_files:
    - "vars/moosefs-settings-regal.yml"

  pre_tasks:
    - name: Print Ansible info useful for development
      debug:
        msg:
          - "{{ ansible_distribution }} {{ ansible_distribution_version }}"

  roles:
    - zorlin.moosefs
