---
# These settings control MooseFS for the default inventory and normal environment.
# Only defaults (from zorlin.moosefs) that are not appropriate for your particular needs are overridden here.
# You can adjust any of this to suit your own installations.
# There is also a production-moosefs-settings.yml which is used by default when using the production inventory,
# and you should use it if possible for your production clusters. They are the real settings I use for my own personal MooseFS.

# The version of MooseFS to install and upgrade to. Only used for machines that need to build from source.
moosefs_version: '3.0.115'
