---
# These settings control the behaviour of the rolling upgrade scripts for managing MooseFS.
# We have provided some sane defaults which you are welcome to change as needed.

# The version of MooseFS to install and upgrade to. Only used for machines that need to build from source.
moosefs_version: '3.0.115'

# Settings for the metaloggers
moosefs_restart_metaloggers: true
moosefs_restart_metaloggers_force: false

# Settings for the master(s)
# not implemented yet

# Settings for the chunkservers
moosefs_restart_chunkservers: true
moosefs_restart_chunkservers_force: false
moosefs_abort_on_missing_chunks: true
moosefs_abort_on_endangered_chunks: true
moosefs_abort_on_undergoal_chunks: false

# Settings for the client(s)
# not implemented yet
